name: Build and Publish Artifact

on:
  push:
    branches:
      - main # Trigger this action on push to main (or your default branch)
  pull_request:
    branches:
      - main # Trigger this action on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Change into the frontend directory
      - name: Change directory to frontend
        run: cd frontend

      # Set up Node.js (use your version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Replace with your required Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: frontend

      # Run build script to generate the artifact
      - name: Build project
        run: npm run build
        working-directory: frontend

      # Upload the build artifact (e.g., 'dist' or 'build' folder)
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: frontend/dist # or ./build (replace with your actual build directory)
